# Generated by Django 4.0.5 on 2022-06-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_alter_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(upload_to='games'),
        ),
    ]
