# Generated by Django 4.0.5 on 2022-07-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_rename__cart_id_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
    ]
